language: node_js

if: tag IS present

node_js:
- 11.10.1

install:
  - npm install webpack webpack-cli -g
  - npm install webpack webpack-cli --save-dev
  - npm install

script:
  - webpack

deploy:
  provider: npm
  edge: true
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: AngusYang9/ele-spreadjs
  skip_cleanup: true

after_deploy:
  - echo npm published!😊
