export const BUTTON_STYLE = `display: inline-block;
    padding: 0 3px;
    height: 30px;
    white-space: nowrap;
    text-align: center;
    border-radius: 4px;
    border: 1px solid #d3d3d3;
    cursor: pointer;
    text-decoration: none;
    outline: 0;
    background-color: #fff;
    position: relative;
    vertical-align: middle;
    min-width: 70px;
    height: 36px;
    font-size: 12px;
    line-height: 34px;
    min-width: 0;
    color: #798194;
    cursor: pointer;
    background: none;
    border-color: transparent;
    `;
export const SPLIT_STYLE = 'color: #adadad;';
export const SELECT_STYLE = `
    border:1px solid #CCC;
    border-radius: 5px;
`;

export const CHECKED_COLOR = '#3795e5';
export const UNCHECKED_COLOR = '#798194';
